// Generated by gencpp from file topp_ros/GenerateTrajectory.msg
// DO NOT EDIT!


#ifndef TOPP_ROS_MESSAGE_GENERATETRAJECTORY_H
#define TOPP_ROS_MESSAGE_GENERATETRAJECTORY_H

#include <ros/service_traits.h>


#include <topp_ros/GenerateTrajectoryRequest.h>
#include <topp_ros/GenerateTrajectoryResponse.h>


namespace topp_ros
{

struct GenerateTrajectory
{

typedef GenerateTrajectoryRequest Request;
typedef GenerateTrajectoryResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GenerateTrajectory
} // namespace topp_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::topp_ros::GenerateTrajectory > {
  static const char* value()
  {
    return "bf5d8c7f17b854de72ace6f948a3f238";
  }

  static const char* value(const ::topp_ros::GenerateTrajectory&) { return value(); }
};

template<>
struct DataType< ::topp_ros::GenerateTrajectory > {
  static const char* value()
  {
    return "topp_ros/GenerateTrajectory";
  }

  static const char* value(const ::topp_ros::GenerateTrajectory&) { return value(); }
};


// service_traits::MD5Sum< ::topp_ros::GenerateTrajectoryRequest> should match
// service_traits::MD5Sum< ::topp_ros::GenerateTrajectory >
template<>
struct MD5Sum< ::topp_ros::GenerateTrajectoryRequest>
{
  static const char* value()
  {
    return MD5Sum< ::topp_ros::GenerateTrajectory >::value();
  }
  static const char* value(const ::topp_ros::GenerateTrajectoryRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::topp_ros::GenerateTrajectoryRequest> should match
// service_traits::DataType< ::topp_ros::GenerateTrajectory >
template<>
struct DataType< ::topp_ros::GenerateTrajectoryRequest>
{
  static const char* value()
  {
    return DataType< ::topp_ros::GenerateTrajectory >::value();
  }
  static const char* value(const ::topp_ros::GenerateTrajectoryRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::topp_ros::GenerateTrajectoryResponse> should match
// service_traits::MD5Sum< ::topp_ros::GenerateTrajectory >
template<>
struct MD5Sum< ::topp_ros::GenerateTrajectoryResponse>
{
  static const char* value()
  {
    return MD5Sum< ::topp_ros::GenerateTrajectory >::value();
  }
  static const char* value(const ::topp_ros::GenerateTrajectoryResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::topp_ros::GenerateTrajectoryResponse> should match
// service_traits::DataType< ::topp_ros::GenerateTrajectory >
template<>
struct DataType< ::topp_ros::GenerateTrajectoryResponse>
{
  static const char* value()
  {
    return DataType< ::topp_ros::GenerateTrajectory >::value();
  }
  static const char* value(const ::topp_ros::GenerateTrajectoryResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TOPP_ROS_MESSAGE_GENERATETRAJECTORY_H
