// Generated by gencpp from file topp_ros/GenerateTrajectoryRequest.msg
// DO NOT EDIT!


#ifndef TOPP_ROS_MESSAGE_GENERATETRAJECTORYREQUEST_H
#define TOPP_ROS_MESSAGE_GENERATETRAJECTORYREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <trajectory_msgs/JointTrajectory.h>

namespace topp_ros
{
template <class ContainerAllocator>
struct GenerateTrajectoryRequest_
{
  typedef GenerateTrajectoryRequest_<ContainerAllocator> Type;

  GenerateTrajectoryRequest_()
    : waypoints()
    , sampling_frequency(0.0)
    , n_gridpoints(0)
    , plot(false)  {
    }
  GenerateTrajectoryRequest_(const ContainerAllocator& _alloc)
    : waypoints(_alloc)
    , sampling_frequency(0.0)
    , n_gridpoints(0)
    , plot(false)  {
  (void)_alloc;
    }



   typedef  ::trajectory_msgs::JointTrajectory_<ContainerAllocator>  _waypoints_type;
  _waypoints_type waypoints;

   typedef double _sampling_frequency_type;
  _sampling_frequency_type sampling_frequency;

   typedef int32_t _n_gridpoints_type;
  _n_gridpoints_type n_gridpoints;

   typedef uint8_t _plot_type;
  _plot_type plot;





  typedef boost::shared_ptr< ::topp_ros::GenerateTrajectoryRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::topp_ros::GenerateTrajectoryRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GenerateTrajectoryRequest_

typedef ::topp_ros::GenerateTrajectoryRequest_<std::allocator<void> > GenerateTrajectoryRequest;

typedef boost::shared_ptr< ::topp_ros::GenerateTrajectoryRequest > GenerateTrajectoryRequestPtr;
typedef boost::shared_ptr< ::topp_ros::GenerateTrajectoryRequest const> GenerateTrajectoryRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::topp_ros::GenerateTrajectoryRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::topp_ros::GenerateTrajectoryRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::topp_ros::GenerateTrajectoryRequest_<ContainerAllocator1> & lhs, const ::topp_ros::GenerateTrajectoryRequest_<ContainerAllocator2> & rhs)
{
  return lhs.waypoints == rhs.waypoints &&
    lhs.sampling_frequency == rhs.sampling_frequency &&
    lhs.n_gridpoints == rhs.n_gridpoints &&
    lhs.plot == rhs.plot;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::topp_ros::GenerateTrajectoryRequest_<ContainerAllocator1> & lhs, const ::topp_ros::GenerateTrajectoryRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace topp_ros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::topp_ros::GenerateTrajectoryRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::topp_ros::GenerateTrajectoryRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::topp_ros::GenerateTrajectoryRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::topp_ros::GenerateTrajectoryRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::topp_ros::GenerateTrajectoryRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::topp_ros::GenerateTrajectoryRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::topp_ros::GenerateTrajectoryRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2a7db67aa372818c32ae772033caea39";
  }

  static const char* value(const ::topp_ros::GenerateTrajectoryRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2a7db67aa372818cULL;
  static const uint64_t static_value2 = 0x32ae772033caea39ULL;
};

template<class ContainerAllocator>
struct DataType< ::topp_ros::GenerateTrajectoryRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "topp_ros/GenerateTrajectoryRequest";
  }

  static const char* value(const ::topp_ros::GenerateTrajectoryRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::topp_ros::GenerateTrajectoryRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "trajectory_msgs/JointTrajectory     waypoints\n"
"float64                             sampling_frequency\n"
"int32                               n_gridpoints\n"
"bool                                plot\n"
"\n"
"================================================================================\n"
"MSG: trajectory_msgs/JointTrajectory\n"
"Header header\n"
"string[] joint_names\n"
"JointTrajectoryPoint[] points\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: trajectory_msgs/JointTrajectoryPoint\n"
"# Each trajectory point specifies either positions[, velocities[, accelerations]]\n"
"# or positions[, effort] for the trajectory to be executed.\n"
"# All specified values are in the same order as the joint names in JointTrajectory.msg\n"
"\n"
"float64[] positions\n"
"float64[] velocities\n"
"float64[] accelerations\n"
"float64[] effort\n"
"duration time_from_start\n"
;
  }

  static const char* value(const ::topp_ros::GenerateTrajectoryRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::topp_ros::GenerateTrajectoryRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.waypoints);
      stream.next(m.sampling_frequency);
      stream.next(m.n_gridpoints);
      stream.next(m.plot);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GenerateTrajectoryRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::topp_ros::GenerateTrajectoryRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::topp_ros::GenerateTrajectoryRequest_<ContainerAllocator>& v)
  {
    s << indent << "waypoints: ";
    s << std::endl;
    Printer< ::trajectory_msgs::JointTrajectory_<ContainerAllocator> >::stream(s, indent + "  ", v.waypoints);
    s << indent << "sampling_frequency: ";
    Printer<double>::stream(s, indent + "  ", v.sampling_frequency);
    s << indent << "n_gridpoints: ";
    Printer<int32_t>::stream(s, indent + "  ", v.n_gridpoints);
    s << indent << "plot: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.plot);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TOPP_ROS_MESSAGE_GENERATETRAJECTORYREQUEST_H
