// Generated by gencpp from file topp_ros/GetHelixPointsResponse.msg
// DO NOT EDIT!


#ifndef TOPP_ROS_MESSAGE_GETHELIXPOINTSRESPONSE_H
#define TOPP_ROS_MESSAGE_GETHELIXPOINTSRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <trajectory_msgs/JointTrajectory.h>

namespace topp_ros
{
template <class ContainerAllocator>
struct GetHelixPointsResponse_
{
  typedef GetHelixPointsResponse_<ContainerAllocator> Type;

  GetHelixPointsResponse_()
    : helix_points()  {
    }
  GetHelixPointsResponse_(const ContainerAllocator& _alloc)
    : helix_points(_alloc)  {
  (void)_alloc;
    }



   typedef  ::trajectory_msgs::JointTrajectory_<ContainerAllocator>  _helix_points_type;
  _helix_points_type helix_points;





  typedef boost::shared_ptr< ::topp_ros::GetHelixPointsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::topp_ros::GetHelixPointsResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetHelixPointsResponse_

typedef ::topp_ros::GetHelixPointsResponse_<std::allocator<void> > GetHelixPointsResponse;

typedef boost::shared_ptr< ::topp_ros::GetHelixPointsResponse > GetHelixPointsResponsePtr;
typedef boost::shared_ptr< ::topp_ros::GetHelixPointsResponse const> GetHelixPointsResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::topp_ros::GetHelixPointsResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::topp_ros::GetHelixPointsResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::topp_ros::GetHelixPointsResponse_<ContainerAllocator1> & lhs, const ::topp_ros::GetHelixPointsResponse_<ContainerAllocator2> & rhs)
{
  return lhs.helix_points == rhs.helix_points;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::topp_ros::GetHelixPointsResponse_<ContainerAllocator1> & lhs, const ::topp_ros::GetHelixPointsResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace topp_ros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::topp_ros::GetHelixPointsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::topp_ros::GetHelixPointsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::topp_ros::GetHelixPointsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::topp_ros::GetHelixPointsResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::topp_ros::GetHelixPointsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::topp_ros::GetHelixPointsResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::topp_ros::GetHelixPointsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7652abeefc2221336a2308c3bf30bca3";
  }

  static const char* value(const ::topp_ros::GetHelixPointsResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7652abeefc222133ULL;
  static const uint64_t static_value2 = 0x6a2308c3bf30bca3ULL;
};

template<class ContainerAllocator>
struct DataType< ::topp_ros::GetHelixPointsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "topp_ros/GetHelixPointsResponse";
  }

  static const char* value(const ::topp_ros::GetHelixPointsResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::topp_ros::GetHelixPointsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "trajectory_msgs/JointTrajectory helix_points\n"
"\n"
"================================================================================\n"
"MSG: trajectory_msgs/JointTrajectory\n"
"Header header\n"
"string[] joint_names\n"
"JointTrajectoryPoint[] points\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: trajectory_msgs/JointTrajectoryPoint\n"
"# Each trajectory point specifies either positions[, velocities[, accelerations]]\n"
"# or positions[, effort] for the trajectory to be executed.\n"
"# All specified values are in the same order as the joint names in JointTrajectory.msg\n"
"\n"
"float64[] positions\n"
"float64[] velocities\n"
"float64[] accelerations\n"
"float64[] effort\n"
"duration time_from_start\n"
;
  }

  static const char* value(const ::topp_ros::GetHelixPointsResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::topp_ros::GetHelixPointsResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.helix_points);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetHelixPointsResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::topp_ros::GetHelixPointsResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::topp_ros::GetHelixPointsResponse_<ContainerAllocator>& v)
  {
    s << indent << "helix_points: ";
    s << std::endl;
    Printer< ::trajectory_msgs::JointTrajectory_<ContainerAllocator> >::stream(s, indent + "  ", v.helix_points);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TOPP_ROS_MESSAGE_GETHELIXPOINTSRESPONSE_H
