// Generated by gencpp from file topp_ros/GetHelixPoints.msg
// DO NOT EDIT!


#ifndef TOPP_ROS_MESSAGE_GETHELIXPOINTS_H
#define TOPP_ROS_MESSAGE_GETHELIXPOINTS_H

#include <ros/service_traits.h>


#include <topp_ros/GetHelixPointsRequest.h>
#include <topp_ros/GetHelixPointsResponse.h>


namespace topp_ros
{

struct GetHelixPoints
{

typedef GetHelixPointsRequest Request;
typedef GetHelixPointsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetHelixPoints
} // namespace topp_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::topp_ros::GetHelixPoints > {
  static const char* value()
  {
    return "822f91513c2ae98aef72e6642f42233f";
  }

  static const char* value(const ::topp_ros::GetHelixPoints&) { return value(); }
};

template<>
struct DataType< ::topp_ros::GetHelixPoints > {
  static const char* value()
  {
    return "topp_ros/GetHelixPoints";
  }

  static const char* value(const ::topp_ros::GetHelixPoints&) { return value(); }
};


// service_traits::MD5Sum< ::topp_ros::GetHelixPointsRequest> should match
// service_traits::MD5Sum< ::topp_ros::GetHelixPoints >
template<>
struct MD5Sum< ::topp_ros::GetHelixPointsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::topp_ros::GetHelixPoints >::value();
  }
  static const char* value(const ::topp_ros::GetHelixPointsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::topp_ros::GetHelixPointsRequest> should match
// service_traits::DataType< ::topp_ros::GetHelixPoints >
template<>
struct DataType< ::topp_ros::GetHelixPointsRequest>
{
  static const char* value()
  {
    return DataType< ::topp_ros::GetHelixPoints >::value();
  }
  static const char* value(const ::topp_ros::GetHelixPointsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::topp_ros::GetHelixPointsResponse> should match
// service_traits::MD5Sum< ::topp_ros::GetHelixPoints >
template<>
struct MD5Sum< ::topp_ros::GetHelixPointsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::topp_ros::GetHelixPoints >::value();
  }
  static const char* value(const ::topp_ros::GetHelixPointsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::topp_ros::GetHelixPointsResponse> should match
// service_traits::DataType< ::topp_ros::GetHelixPoints >
template<>
struct DataType< ::topp_ros::GetHelixPointsResponse>
{
  static const char* value()
  {
    return DataType< ::topp_ros::GetHelixPoints >::value();
  }
  static const char* value(const ::topp_ros::GetHelixPointsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TOPP_ROS_MESSAGE_GETHELIXPOINTS_H
