//#line 2 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"
// *********************************************************
//
// File autogenerated for the gremsy_base package
// by the dynamic_reconfigure package.
// Please do not edit.
//
// ********************************************************/

#ifndef __gremsy_base__ROSGREMSYCONFIG_H__
#define __gremsy_base__ROSGREMSYCONFIG_H__

#if __cplusplus >= 201103L
#define DYNAMIC_RECONFIGURE_FINAL final
#else
#define DYNAMIC_RECONFIGURE_FINAL
#endif

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace gremsy_base
{
  class ROSGremsyConfigStatics;

  class ROSGremsyConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l,
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }
      virtual ~AbstractParamDescription() = default;

      virtual void clamp(ROSGremsyConfig &config, const ROSGremsyConfig &max, const ROSGremsyConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const ROSGremsyConfig &config1, const ROSGremsyConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, ROSGremsyConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const ROSGremsyConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, ROSGremsyConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const ROSGremsyConfig &config) const = 0;
      virtual void getValue(const ROSGremsyConfig &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template <class T>
    class ParamDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string a_name, std::string a_type, uint32_t a_level,
          std::string a_description, std::string a_edit_method, T ROSGremsyConfig::* a_f) :
        AbstractParamDescription(a_name, a_type, a_level, a_description, a_edit_method),
        field(a_f)
      {}

      T ROSGremsyConfig::* field;

      virtual void clamp(ROSGremsyConfig &config, const ROSGremsyConfig &max, const ROSGremsyConfig &min) const override
      {
        if (config.*field > max.*field)
          config.*field = max.*field;

        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const ROSGremsyConfig &config1, const ROSGremsyConfig &config2) const override
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, ROSGremsyConfig &config) const override
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const ROSGremsyConfig &config) const override
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, ROSGremsyConfig &config) const override
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const ROSGremsyConfig &config) const override
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const ROSGremsyConfig &config, boost::any &val) const override
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      virtual ~AbstractGroupDescription() = default;

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, ROSGremsyConfig &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); ++i)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template<class T, class PT>
    class GroupDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string a_name, std::string a_type, int a_parent, int a_id, bool a_s, T PT::* a_f) : AbstractGroupDescription(a_name, a_type, a_parent, a_id, a_s), field(a_f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }

      virtual void updateParams(boost::any &cfg, ROSGremsyConfig &top) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const override
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T PT::* field;
      std::vector<ROSGremsyConfig::AbstractGroupDescriptionConstPtr> groups;
    };

class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(ROSGremsyConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("device"==(*_i)->name){device = boost::any_cast<std::string>(val);}
        if("baudrate"==(*_i)->name){baudrate = boost::any_cast<int>(val);}
        if("state_poll_rate"==(*_i)->name){state_poll_rate = boost::any_cast<double>(val);}
        if("goal_push_rate"==(*_i)->name){goal_push_rate = boost::any_cast<double>(val);}
        if("gimbal_mode"==(*_i)->name){gimbal_mode = boost::any_cast<int>(val);}
        if("tilt_axis_input_mode"==(*_i)->name){tilt_axis_input_mode = boost::any_cast<int>(val);}
        if("tilt_axis_stabilize"==(*_i)->name){tilt_axis_stabilize = boost::any_cast<bool>(val);}
        if("roll_axis_input_mode"==(*_i)->name){roll_axis_input_mode = boost::any_cast<int>(val);}
        if("roll_axis_stabilize"==(*_i)->name){roll_axis_stabilize = boost::any_cast<bool>(val);}
        if("pan_axis_input_mode"==(*_i)->name){pan_axis_input_mode = boost::any_cast<int>(val);}
        if("pan_axis_stabilize"==(*_i)->name){pan_axis_stabilize = boost::any_cast<bool>(val);}
        if("lock_yaw_to_vehicle"==(*_i)->name){lock_yaw_to_vehicle = boost::any_cast<bool>(val);}
      }
    }

    std::string device;
int baudrate;
double state_poll_rate;
double goal_push_rate;
int gimbal_mode;
int tilt_axis_input_mode;
bool tilt_axis_stabilize;
int roll_axis_input_mode;
bool roll_axis_stabilize;
int pan_axis_input_mode;
bool pan_axis_stabilize;
bool lock_yaw_to_vehicle;

    bool state;
    std::string name;

    
}groups;



//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      std::string device;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int baudrate;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double state_poll_rate;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double goal_push_rate;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int gimbal_mode;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int tilt_axis_input_mode;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      bool tilt_axis_stabilize;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int roll_axis_input_mode;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      bool roll_axis_stabilize;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int pan_axis_input_mode;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      bool pan_axis_stabilize;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      bool lock_yaw_to_vehicle;
//#line 231 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("ROSGremsyConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }

    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }

    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const ROSGremsyConfig &__max__ = __getMax__();
      const ROSGremsyConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const ROSGremsyConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->calcLevel(level, config, *this);
      return level;
    }

    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const ROSGremsyConfig &__getDefault__();
    static const ROSGremsyConfig &__getMax__();
    static const ROSGremsyConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();

  private:
    static const ROSGremsyConfigStatics *__get_statics__();
  };

  template <> // Max and min are ignored for strings.
  inline void ROSGremsyConfig::ParamDescription<std::string>::clamp(ROSGremsyConfig &config, const ROSGremsyConfig &max, const ROSGremsyConfig &min) const
  {
    (void) config;
    (void) min;
    (void) max;
    return;
  }

  class ROSGremsyConfigStatics
  {
    friend class ROSGremsyConfig;

    ROSGremsyConfigStatics()
    {
ROSGremsyConfig::GroupDescription<ROSGremsyConfig::DEFAULT, ROSGremsyConfig> Default("Default", "", 0, 0, true, &ROSGremsyConfig::groups);
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.device = "";
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.device = "";
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.device = "";
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ROSGremsyConfig::AbstractParamDescriptionConstPtr(new ROSGremsyConfig::ParamDescription<std::string>("device", "str", 0, "Serial device for the gimbal connection", "", &ROSGremsyConfig::device)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ROSGremsyConfig::AbstractParamDescriptionConstPtr(new ROSGremsyConfig::ParamDescription<std::string>("device", "str", 0, "Serial device for the gimbal connection", "", &ROSGremsyConfig::device)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.baudrate = -2147483648;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.baudrate = 2147483647;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.baudrate = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ROSGremsyConfig::AbstractParamDescriptionConstPtr(new ROSGremsyConfig::ParamDescription<int>("baudrate", "int", 0, "Baudrate for the gimbal connection", "", &ROSGremsyConfig::baudrate)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ROSGremsyConfig::AbstractParamDescriptionConstPtr(new ROSGremsyConfig::ParamDescription<int>("baudrate", "int", 0, "Baudrate for the gimbal connection", "", &ROSGremsyConfig::baudrate)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.state_poll_rate = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.state_poll_rate = 300.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.state_poll_rate = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ROSGremsyConfig::AbstractParamDescriptionConstPtr(new ROSGremsyConfig::ParamDescription<double>("state_poll_rate", "double", 0, "Rate in which the gimbal data is polled and published", "", &ROSGremsyConfig::state_poll_rate)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ROSGremsyConfig::AbstractParamDescriptionConstPtr(new ROSGremsyConfig::ParamDescription<double>("state_poll_rate", "double", 0, "Rate in which the gimbal data is polled and published", "", &ROSGremsyConfig::state_poll_rate)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.goal_push_rate = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.goal_push_rate = 300.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.goal_push_rate = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ROSGremsyConfig::AbstractParamDescriptionConstPtr(new ROSGremsyConfig::ParamDescription<double>("goal_push_rate", "double", 0, "Rate in which the gimbal are pushed to the gimbal", "", &ROSGremsyConfig::goal_push_rate)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ROSGremsyConfig::AbstractParamDescriptionConstPtr(new ROSGremsyConfig::ParamDescription<double>("goal_push_rate", "double", 0, "Rate in which the gimbal are pushed to the gimbal", "", &ROSGremsyConfig::goal_push_rate)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.gimbal_mode = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.gimbal_mode = 2;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.gimbal_mode = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ROSGremsyConfig::AbstractParamDescriptionConstPtr(new ROSGremsyConfig::ParamDescription<int>("gimbal_mode", "int", 0, "Control mode of the gimbal", "", &ROSGremsyConfig::gimbal_mode)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ROSGremsyConfig::AbstractParamDescriptionConstPtr(new ROSGremsyConfig::ParamDescription<int>("gimbal_mode", "int", 0, "Control mode of the gimbal", "", &ROSGremsyConfig::gimbal_mode)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.tilt_axis_input_mode = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.tilt_axis_input_mode = 2;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.tilt_axis_input_mode = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ROSGremsyConfig::AbstractParamDescriptionConstPtr(new ROSGremsyConfig::ParamDescription<int>("tilt_axis_input_mode", "int", 0, "Input mode of the gimbals tilt axis", "", &ROSGremsyConfig::tilt_axis_input_mode)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ROSGremsyConfig::AbstractParamDescriptionConstPtr(new ROSGremsyConfig::ParamDescription<int>("tilt_axis_input_mode", "int", 0, "Input mode of the gimbals tilt axis", "", &ROSGremsyConfig::tilt_axis_input_mode)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.tilt_axis_stabilize = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.tilt_axis_stabilize = 1;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.tilt_axis_stabilize = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ROSGremsyConfig::AbstractParamDescriptionConstPtr(new ROSGremsyConfig::ParamDescription<bool>("tilt_axis_stabilize", "bool", 0, "Input mode of the gimbals tilt axis", "", &ROSGremsyConfig::tilt_axis_stabilize)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ROSGremsyConfig::AbstractParamDescriptionConstPtr(new ROSGremsyConfig::ParamDescription<bool>("tilt_axis_stabilize", "bool", 0, "Input mode of the gimbals tilt axis", "", &ROSGremsyConfig::tilt_axis_stabilize)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.roll_axis_input_mode = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.roll_axis_input_mode = 2;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.roll_axis_input_mode = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ROSGremsyConfig::AbstractParamDescriptionConstPtr(new ROSGremsyConfig::ParamDescription<int>("roll_axis_input_mode", "int", 0, "Input mode of the gimbals tilt roll", "", &ROSGremsyConfig::roll_axis_input_mode)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ROSGremsyConfig::AbstractParamDescriptionConstPtr(new ROSGremsyConfig::ParamDescription<int>("roll_axis_input_mode", "int", 0, "Input mode of the gimbals tilt roll", "", &ROSGremsyConfig::roll_axis_input_mode)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.roll_axis_stabilize = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.roll_axis_stabilize = 1;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.roll_axis_stabilize = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ROSGremsyConfig::AbstractParamDescriptionConstPtr(new ROSGremsyConfig::ParamDescription<bool>("roll_axis_stabilize", "bool", 0, "Input mode of the gimbals tilt roll", "", &ROSGremsyConfig::roll_axis_stabilize)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ROSGremsyConfig::AbstractParamDescriptionConstPtr(new ROSGremsyConfig::ParamDescription<bool>("roll_axis_stabilize", "bool", 0, "Input mode of the gimbals tilt roll", "", &ROSGremsyConfig::roll_axis_stabilize)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.pan_axis_input_mode = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.pan_axis_input_mode = 2;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.pan_axis_input_mode = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ROSGremsyConfig::AbstractParamDescriptionConstPtr(new ROSGremsyConfig::ParamDescription<int>("pan_axis_input_mode", "int", 0, "Input mode of the gimbals tilt pan", "", &ROSGremsyConfig::pan_axis_input_mode)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ROSGremsyConfig::AbstractParamDescriptionConstPtr(new ROSGremsyConfig::ParamDescription<int>("pan_axis_input_mode", "int", 0, "Input mode of the gimbals tilt pan", "", &ROSGremsyConfig::pan_axis_input_mode)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.pan_axis_stabilize = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.pan_axis_stabilize = 1;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.pan_axis_stabilize = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ROSGremsyConfig::AbstractParamDescriptionConstPtr(new ROSGremsyConfig::ParamDescription<bool>("pan_axis_stabilize", "bool", 0, "Input mode of the gimbals tilt pan", "", &ROSGremsyConfig::pan_axis_stabilize)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ROSGremsyConfig::AbstractParamDescriptionConstPtr(new ROSGremsyConfig::ParamDescription<bool>("pan_axis_stabilize", "bool", 0, "Input mode of the gimbals tilt pan", "", &ROSGremsyConfig::pan_axis_stabilize)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.lock_yaw_to_vehicle = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.lock_yaw_to_vehicle = 1;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.lock_yaw_to_vehicle = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ROSGremsyConfig::AbstractParamDescriptionConstPtr(new ROSGremsyConfig::ParamDescription<bool>("lock_yaw_to_vehicle", "bool", 0, "Uses the yaw relative to the gimbal mount to prevent drift issues. Only a light stabilization is applied.", "", &ROSGremsyConfig::lock_yaw_to_vehicle)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ROSGremsyConfig::AbstractParamDescriptionConstPtr(new ROSGremsyConfig::ParamDescription<bool>("lock_yaw_to_vehicle", "bool", 0, "Uses the yaw relative to the gimbal mount to prevent drift issues. Only a light stabilization is applied.", "", &ROSGremsyConfig::lock_yaw_to_vehicle)));
//#line 246 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.convertParams();
//#line 246 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(ROSGremsyConfig::AbstractGroupDescriptionConstPtr(new ROSGremsyConfig::GroupDescription<ROSGremsyConfig::DEFAULT, ROSGremsyConfig>(Default)));
//#line 369 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

      for (std::vector<ROSGremsyConfig::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__);
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__);
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__);
    }
    std::vector<ROSGremsyConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<ROSGremsyConfig::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    ROSGremsyConfig __max__;
    ROSGremsyConfig __min__;
    ROSGremsyConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const ROSGremsyConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static ROSGremsyConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &ROSGremsyConfig::__getDescriptionMessage__()
  {
    return __get_statics__()->__description_message__;
  }

  inline const ROSGremsyConfig &ROSGremsyConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }

  inline const ROSGremsyConfig &ROSGremsyConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }

  inline const ROSGremsyConfig &ROSGremsyConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }

  inline const std::vector<ROSGremsyConfig::AbstractParamDescriptionConstPtr> &ROSGremsyConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<ROSGremsyConfig::AbstractGroupDescriptionConstPtr> &ROSGremsyConfig::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const ROSGremsyConfigStatics *ROSGremsyConfig::__get_statics__()
  {
    const static ROSGremsyConfigStatics *statics;

    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = ROSGremsyConfigStatics::get_instance();

    return statics;
  }


}

#undef DYNAMIC_RECONFIGURE_FINAL

#endif // __ROSGREMSYRECONFIGURATOR_H__
