//#line 2 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"
// *********************************************************
//
// File autogenerated for the uav_ros_control package
// by the dynamic_reconfigure package.
// Please do not edit.
//
// ********************************************************/

#ifndef __uav_ros_control__POSITIONCONTROLPARAMETERSCONFIG_H__
#define __uav_ros_control__POSITIONCONTROLPARAMETERSCONFIG_H__

#if __cplusplus >= 201103L
#define DYNAMIC_RECONFIGURE_FINAL final
#else
#define DYNAMIC_RECONFIGURE_FINAL
#endif

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace uav_ros_control
{
  class PositionControlParametersConfigStatics;

  class PositionControlParametersConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l,
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }
      virtual ~AbstractParamDescription() = default;

      virtual void clamp(PositionControlParametersConfig &config, const PositionControlParametersConfig &max, const PositionControlParametersConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const PositionControlParametersConfig &config1, const PositionControlParametersConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, PositionControlParametersConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const PositionControlParametersConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, PositionControlParametersConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const PositionControlParametersConfig &config) const = 0;
      virtual void getValue(const PositionControlParametersConfig &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template <class T>
    class ParamDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string a_name, std::string a_type, uint32_t a_level,
          std::string a_description, std::string a_edit_method, T PositionControlParametersConfig::* a_f) :
        AbstractParamDescription(a_name, a_type, a_level, a_description, a_edit_method),
        field(a_f)
      {}

      T PositionControlParametersConfig::* field;

      virtual void clamp(PositionControlParametersConfig &config, const PositionControlParametersConfig &max, const PositionControlParametersConfig &min) const override
      {
        if (config.*field > max.*field)
          config.*field = max.*field;

        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const PositionControlParametersConfig &config1, const PositionControlParametersConfig &config2) const override
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, PositionControlParametersConfig &config) const override
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const PositionControlParametersConfig &config) const override
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, PositionControlParametersConfig &config) const override
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const PositionControlParametersConfig &config) const override
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const PositionControlParametersConfig &config, boost::any &val) const override
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      virtual ~AbstractGroupDescription() = default;

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, PositionControlParametersConfig &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); ++i)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template<class T, class PT>
    class GroupDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string a_name, std::string a_type, int a_parent, int a_id, bool a_s, T PT::* a_f) : AbstractGroupDescription(a_name, a_type, a_parent, a_id, a_s), field(a_f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }

      virtual void updateParams(boost::any &cfg, PositionControlParametersConfig &top) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const override
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T PT::* field;
      std::vector<PositionControlParametersConfig::AbstractGroupDescriptionConstPtr> groups;
    };

class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(PositionControlParametersConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("hover"==(*_i)->name){hover = boost::any_cast<double>(val);}
        if("k_p_xy"==(*_i)->name){k_p_xy = boost::any_cast<double>(val);}
        if("k_i_xy"==(*_i)->name){k_i_xy = boost::any_cast<double>(val);}
        if("k_d_xy"==(*_i)->name){k_d_xy = boost::any_cast<double>(val);}
        if("lim_high_xy"==(*_i)->name){lim_high_xy = boost::any_cast<double>(val);}
        if("lim_low_xy"==(*_i)->name){lim_low_xy = boost::any_cast<double>(val);}
        if("k_p_vxy"==(*_i)->name){k_p_vxy = boost::any_cast<double>(val);}
        if("k_i_vxy"==(*_i)->name){k_i_vxy = boost::any_cast<double>(val);}
        if("k_d_vxy"==(*_i)->name){k_d_vxy = boost::any_cast<double>(val);}
        if("lim_high_vxy"==(*_i)->name){lim_high_vxy = boost::any_cast<double>(val);}
        if("lim_low_vxy"==(*_i)->name){lim_low_vxy = boost::any_cast<double>(val);}
        if("k_p_z"==(*_i)->name){k_p_z = boost::any_cast<double>(val);}
        if("k_i_z"==(*_i)->name){k_i_z = boost::any_cast<double>(val);}
        if("k_d_z"==(*_i)->name){k_d_z = boost::any_cast<double>(val);}
        if("lim_high_z"==(*_i)->name){lim_high_z = boost::any_cast<double>(val);}
        if("lim_low_z"==(*_i)->name){lim_low_z = boost::any_cast<double>(val);}
        if("k_p_vz"==(*_i)->name){k_p_vz = boost::any_cast<double>(val);}
        if("k_i_vz"==(*_i)->name){k_i_vz = boost::any_cast<double>(val);}
        if("k_d_vz"==(*_i)->name){k_d_vz = boost::any_cast<double>(val);}
        if("lim_high_vz"==(*_i)->name){lim_high_vz = boost::any_cast<double>(val);}
        if("lim_low_vz"==(*_i)->name){lim_low_vz = boost::any_cast<double>(val);}
        if("yaw_rate_p"==(*_i)->name){yaw_rate_p = boost::any_cast<double>(val);}
        if("yaw_rate_i"==(*_i)->name){yaw_rate_i = boost::any_cast<double>(val);}
        if("yaw_rate_d"==(*_i)->name){yaw_rate_d = boost::any_cast<double>(val);}
        if("yaw_rate_lim_high"==(*_i)->name){yaw_rate_lim_high = boost::any_cast<double>(val);}
        if("yaw_rate_lim_low"==(*_i)->name){yaw_rate_lim_low = boost::any_cast<double>(val);}
        if("ff_vel_x"==(*_i)->name){ff_vel_x = boost::any_cast<double>(val);}
        if("ff_vel_y"==(*_i)->name){ff_vel_y = boost::any_cast<double>(val);}
        if("ff_vel_z"==(*_i)->name){ff_vel_z = boost::any_cast<double>(val);}
        if("ff_acc_x"==(*_i)->name){ff_acc_x = boost::any_cast<double>(val);}
        if("ff_acc_y"==(*_i)->name){ff_acc_y = boost::any_cast<double>(val);}
        if("ff_acc_z"==(*_i)->name){ff_acc_z = boost::any_cast<double>(val);}
      }
    }

    double hover;
double k_p_xy;
double k_i_xy;
double k_d_xy;
double lim_high_xy;
double lim_low_xy;
double k_p_vxy;
double k_i_vxy;
double k_d_vxy;
double lim_high_vxy;
double lim_low_vxy;
double k_p_z;
double k_i_z;
double k_d_z;
double lim_high_z;
double lim_low_z;
double k_p_vz;
double k_i_vz;
double k_d_vz;
double lim_high_vz;
double lim_low_vz;
double yaw_rate_p;
double yaw_rate_i;
double yaw_rate_d;
double yaw_rate_lim_high;
double yaw_rate_lim_low;
double ff_vel_x;
double ff_vel_y;
double ff_vel_z;
double ff_acc_x;
double ff_acc_y;
double ff_acc_z;

    bool state;
    std::string name;

    
}groups;



//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double hover;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double k_p_xy;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double k_i_xy;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double k_d_xy;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double lim_high_xy;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double lim_low_xy;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double k_p_vxy;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double k_i_vxy;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double k_d_vxy;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double lim_high_vxy;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double lim_low_vxy;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double k_p_z;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double k_i_z;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double k_d_z;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double lim_high_z;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double lim_low_z;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double k_p_vz;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double k_i_vz;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double k_d_vz;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double lim_high_vz;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double lim_low_vz;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double yaw_rate_p;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double yaw_rate_i;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double yaw_rate_d;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double yaw_rate_lim_high;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double yaw_rate_lim_low;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double ff_vel_x;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double ff_vel_y;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double ff_vel_z;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double ff_acc_x;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double ff_acc_y;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double ff_acc_z;
//#line 231 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("PositionControlParametersConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }

    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }

    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const PositionControlParametersConfig &__max__ = __getMax__();
      const PositionControlParametersConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const PositionControlParametersConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->calcLevel(level, config, *this);
      return level;
    }

    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const PositionControlParametersConfig &__getDefault__();
    static const PositionControlParametersConfig &__getMax__();
    static const PositionControlParametersConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();

  private:
    static const PositionControlParametersConfigStatics *__get_statics__();
  };

  template <> // Max and min are ignored for strings.
  inline void PositionControlParametersConfig::ParamDescription<std::string>::clamp(PositionControlParametersConfig &config, const PositionControlParametersConfig &max, const PositionControlParametersConfig &min) const
  {
    (void) config;
    (void) min;
    (void) max;
    return;
  }

  class PositionControlParametersConfigStatics
  {
    friend class PositionControlParametersConfig;

    PositionControlParametersConfigStatics()
    {
PositionControlParametersConfig::GroupDescription<PositionControlParametersConfig::DEFAULT, PositionControlParametersConfig> Default("Default", "", 0, 0, true, &PositionControlParametersConfig::groups);
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.hover = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.hover = 1.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.hover = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PositionControlParametersConfig::AbstractParamDescriptionConstPtr(new PositionControlParametersConfig::ParamDescription<double>("hover", "double", 0, "Hover thrust", "", &PositionControlParametersConfig::hover)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PositionControlParametersConfig::AbstractParamDescriptionConstPtr(new PositionControlParametersConfig::ParamDescription<double>("hover", "double", 0, "Hover thrust", "", &PositionControlParametersConfig::hover)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.k_p_xy = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.k_p_xy = 100.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.k_p_xy = 5.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PositionControlParametersConfig::AbstractParamDescriptionConstPtr(new PositionControlParametersConfig::ParamDescription<double>("k_p_xy", "double", 0, "Position controller (xy-axes) proportional gain", "", &PositionControlParametersConfig::k_p_xy)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PositionControlParametersConfig::AbstractParamDescriptionConstPtr(new PositionControlParametersConfig::ParamDescription<double>("k_p_xy", "double", 0, "Position controller (xy-axes) proportional gain", "", &PositionControlParametersConfig::k_p_xy)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.k_i_xy = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.k_i_xy = 10.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.k_i_xy = 5.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PositionControlParametersConfig::AbstractParamDescriptionConstPtr(new PositionControlParametersConfig::ParamDescription<double>("k_i_xy", "double", 0, "Position controller (xy-axes) integrator gain", "", &PositionControlParametersConfig::k_i_xy)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PositionControlParametersConfig::AbstractParamDescriptionConstPtr(new PositionControlParametersConfig::ParamDescription<double>("k_i_xy", "double", 0, "Position controller (xy-axes) integrator gain", "", &PositionControlParametersConfig::k_i_xy)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.k_d_xy = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.k_d_xy = 10.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.k_d_xy = 5.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PositionControlParametersConfig::AbstractParamDescriptionConstPtr(new PositionControlParametersConfig::ParamDescription<double>("k_d_xy", "double", 0, "Position controller (xy-axes) derivator gain", "", &PositionControlParametersConfig::k_d_xy)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PositionControlParametersConfig::AbstractParamDescriptionConstPtr(new PositionControlParametersConfig::ParamDescription<double>("k_d_xy", "double", 0, "Position controller (xy-axes) derivator gain", "", &PositionControlParametersConfig::k_d_xy)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.lim_high_xy = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.lim_high_xy = 400.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.lim_high_xy = 0.5;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PositionControlParametersConfig::AbstractParamDescriptionConstPtr(new PositionControlParametersConfig::ParamDescription<double>("lim_high_xy", "double", 0, "Position controller (xy-axes) limit - high", "", &PositionControlParametersConfig::lim_high_xy)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PositionControlParametersConfig::AbstractParamDescriptionConstPtr(new PositionControlParametersConfig::ParamDescription<double>("lim_high_xy", "double", 0, "Position controller (xy-axes) limit - high", "", &PositionControlParametersConfig::lim_high_xy)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.lim_low_xy = -400.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.lim_low_xy = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.lim_low_xy = -0.5;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PositionControlParametersConfig::AbstractParamDescriptionConstPtr(new PositionControlParametersConfig::ParamDescription<double>("lim_low_xy", "double", 0, "Position controller (xy-axes) limit - low", "", &PositionControlParametersConfig::lim_low_xy)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PositionControlParametersConfig::AbstractParamDescriptionConstPtr(new PositionControlParametersConfig::ParamDescription<double>("lim_low_xy", "double", 0, "Position controller (xy-axes) limit - low", "", &PositionControlParametersConfig::lim_low_xy)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.k_p_vxy = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.k_p_vxy = 100.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.k_p_vxy = 5.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PositionControlParametersConfig::AbstractParamDescriptionConstPtr(new PositionControlParametersConfig::ParamDescription<double>("k_p_vxy", "double", 0, "Velocity controller (xy-axes) proportional gain", "", &PositionControlParametersConfig::k_p_vxy)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PositionControlParametersConfig::AbstractParamDescriptionConstPtr(new PositionControlParametersConfig::ParamDescription<double>("k_p_vxy", "double", 0, "Velocity controller (xy-axes) proportional gain", "", &PositionControlParametersConfig::k_p_vxy)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.k_i_vxy = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.k_i_vxy = 10.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.k_i_vxy = 5.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PositionControlParametersConfig::AbstractParamDescriptionConstPtr(new PositionControlParametersConfig::ParamDescription<double>("k_i_vxy", "double", 0, "Velocity controller (xy-axes) integrator gain", "", &PositionControlParametersConfig::k_i_vxy)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PositionControlParametersConfig::AbstractParamDescriptionConstPtr(new PositionControlParametersConfig::ParamDescription<double>("k_i_vxy", "double", 0, "Velocity controller (xy-axes) integrator gain", "", &PositionControlParametersConfig::k_i_vxy)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.k_d_vxy = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.k_d_vxy = 10.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.k_d_vxy = 5.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PositionControlParametersConfig::AbstractParamDescriptionConstPtr(new PositionControlParametersConfig::ParamDescription<double>("k_d_vxy", "double", 0, "Velocity controller (xy-axes) derivator gain", "", &PositionControlParametersConfig::k_d_vxy)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PositionControlParametersConfig::AbstractParamDescriptionConstPtr(new PositionControlParametersConfig::ParamDescription<double>("k_d_vxy", "double", 0, "Velocity controller (xy-axes) derivator gain", "", &PositionControlParametersConfig::k_d_vxy)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.lim_high_vxy = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.lim_high_vxy = 400.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.lim_high_vxy = 0.5;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PositionControlParametersConfig::AbstractParamDescriptionConstPtr(new PositionControlParametersConfig::ParamDescription<double>("lim_high_vxy", "double", 0, "Velocity controller (xy-axes) limit - high", "", &PositionControlParametersConfig::lim_high_vxy)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PositionControlParametersConfig::AbstractParamDescriptionConstPtr(new PositionControlParametersConfig::ParamDescription<double>("lim_high_vxy", "double", 0, "Velocity controller (xy-axes) limit - high", "", &PositionControlParametersConfig::lim_high_vxy)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.lim_low_vxy = -400.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.lim_low_vxy = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.lim_low_vxy = -0.5;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PositionControlParametersConfig::AbstractParamDescriptionConstPtr(new PositionControlParametersConfig::ParamDescription<double>("lim_low_vxy", "double", 0, "Velocity controller (xy-axes) limit - low", "", &PositionControlParametersConfig::lim_low_vxy)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PositionControlParametersConfig::AbstractParamDescriptionConstPtr(new PositionControlParametersConfig::ParamDescription<double>("lim_low_vxy", "double", 0, "Velocity controller (xy-axes) limit - low", "", &PositionControlParametersConfig::lim_low_vxy)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.k_p_z = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.k_p_z = 100.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.k_p_z = 5.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PositionControlParametersConfig::AbstractParamDescriptionConstPtr(new PositionControlParametersConfig::ParamDescription<double>("k_p_z", "double", 0, "Position controller (z-axis) proportional gain", "", &PositionControlParametersConfig::k_p_z)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PositionControlParametersConfig::AbstractParamDescriptionConstPtr(new PositionControlParametersConfig::ParamDescription<double>("k_p_z", "double", 0, "Position controller (z-axis) proportional gain", "", &PositionControlParametersConfig::k_p_z)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.k_i_z = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.k_i_z = 100.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.k_i_z = 5.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PositionControlParametersConfig::AbstractParamDescriptionConstPtr(new PositionControlParametersConfig::ParamDescription<double>("k_i_z", "double", 0, "Position controller (z-axis) integrator gain", "", &PositionControlParametersConfig::k_i_z)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PositionControlParametersConfig::AbstractParamDescriptionConstPtr(new PositionControlParametersConfig::ParamDescription<double>("k_i_z", "double", 0, "Position controller (z-axis) integrator gain", "", &PositionControlParametersConfig::k_i_z)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.k_d_z = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.k_d_z = 100.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.k_d_z = 5.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PositionControlParametersConfig::AbstractParamDescriptionConstPtr(new PositionControlParametersConfig::ParamDescription<double>("k_d_z", "double", 0, "Position controller (z-axis) derivator gain", "", &PositionControlParametersConfig::k_d_z)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PositionControlParametersConfig::AbstractParamDescriptionConstPtr(new PositionControlParametersConfig::ParamDescription<double>("k_d_z", "double", 0, "Position controller (z-axis) derivator gain", "", &PositionControlParametersConfig::k_d_z)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.lim_high_z = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.lim_high_z = 50.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.lim_high_z = 0.5;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PositionControlParametersConfig::AbstractParamDescriptionConstPtr(new PositionControlParametersConfig::ParamDescription<double>("lim_high_z", "double", 0, "Position controller (z-axis) limit - high", "", &PositionControlParametersConfig::lim_high_z)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PositionControlParametersConfig::AbstractParamDescriptionConstPtr(new PositionControlParametersConfig::ParamDescription<double>("lim_high_z", "double", 0, "Position controller (z-axis) limit - high", "", &PositionControlParametersConfig::lim_high_z)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.lim_low_z = -50.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.lim_low_z = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.lim_low_z = -0.5;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PositionControlParametersConfig::AbstractParamDescriptionConstPtr(new PositionControlParametersConfig::ParamDescription<double>("lim_low_z", "double", 0, "Position controller (z-axis) limit - low", "", &PositionControlParametersConfig::lim_low_z)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PositionControlParametersConfig::AbstractParamDescriptionConstPtr(new PositionControlParametersConfig::ParamDescription<double>("lim_low_z", "double", 0, "Position controller (z-axis) limit - low", "", &PositionControlParametersConfig::lim_low_z)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.k_p_vz = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.k_p_vz = 10.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.k_p_vz = 5.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PositionControlParametersConfig::AbstractParamDescriptionConstPtr(new PositionControlParametersConfig::ParamDescription<double>("k_p_vz", "double", 0, "Velocity controller (z-axis) proportional gain", "", &PositionControlParametersConfig::k_p_vz)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PositionControlParametersConfig::AbstractParamDescriptionConstPtr(new PositionControlParametersConfig::ParamDescription<double>("k_p_vz", "double", 0, "Velocity controller (z-axis) proportional gain", "", &PositionControlParametersConfig::k_p_vz)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.k_i_vz = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.k_i_vz = 10.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.k_i_vz = 5.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PositionControlParametersConfig::AbstractParamDescriptionConstPtr(new PositionControlParametersConfig::ParamDescription<double>("k_i_vz", "double", 0, "Velocity controller (z-axis) integrator gain", "", &PositionControlParametersConfig::k_i_vz)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PositionControlParametersConfig::AbstractParamDescriptionConstPtr(new PositionControlParametersConfig::ParamDescription<double>("k_i_vz", "double", 0, "Velocity controller (z-axis) integrator gain", "", &PositionControlParametersConfig::k_i_vz)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.k_d_vz = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.k_d_vz = 10.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.k_d_vz = 5.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PositionControlParametersConfig::AbstractParamDescriptionConstPtr(new PositionControlParametersConfig::ParamDescription<double>("k_d_vz", "double", 0, "Velocity controller (z-axis) derivator gain", "", &PositionControlParametersConfig::k_d_vz)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PositionControlParametersConfig::AbstractParamDescriptionConstPtr(new PositionControlParametersConfig::ParamDescription<double>("k_d_vz", "double", 0, "Velocity controller (z-axis) derivator gain", "", &PositionControlParametersConfig::k_d_vz)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.lim_high_vz = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.lim_high_vz = 50.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.lim_high_vz = 0.5;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PositionControlParametersConfig::AbstractParamDescriptionConstPtr(new PositionControlParametersConfig::ParamDescription<double>("lim_high_vz", "double", 0, "Velocity controller (z-axis) limit - high", "", &PositionControlParametersConfig::lim_high_vz)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PositionControlParametersConfig::AbstractParamDescriptionConstPtr(new PositionControlParametersConfig::ParamDescription<double>("lim_high_vz", "double", 0, "Velocity controller (z-axis) limit - high", "", &PositionControlParametersConfig::lim_high_vz)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.lim_low_vz = -50.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.lim_low_vz = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.lim_low_vz = -0.5;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PositionControlParametersConfig::AbstractParamDescriptionConstPtr(new PositionControlParametersConfig::ParamDescription<double>("lim_low_vz", "double", 0, "Velocity controller (z-axis) limit - low", "", &PositionControlParametersConfig::lim_low_vz)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PositionControlParametersConfig::AbstractParamDescriptionConstPtr(new PositionControlParametersConfig::ParamDescription<double>("lim_low_vz", "double", 0, "Velocity controller (z-axis) limit - low", "", &PositionControlParametersConfig::lim_low_vz)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.yaw_rate_p = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.yaw_rate_p = 10.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.yaw_rate_p = 5.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PositionControlParametersConfig::AbstractParamDescriptionConstPtr(new PositionControlParametersConfig::ParamDescription<double>("yaw_rate_p", "double", 0, "Yaw-rate controller proportional gain", "", &PositionControlParametersConfig::yaw_rate_p)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PositionControlParametersConfig::AbstractParamDescriptionConstPtr(new PositionControlParametersConfig::ParamDescription<double>("yaw_rate_p", "double", 0, "Yaw-rate controller proportional gain", "", &PositionControlParametersConfig::yaw_rate_p)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.yaw_rate_i = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.yaw_rate_i = 10.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.yaw_rate_i = 5.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PositionControlParametersConfig::AbstractParamDescriptionConstPtr(new PositionControlParametersConfig::ParamDescription<double>("yaw_rate_i", "double", 0, "Yaw-rate controller integrator gain", "", &PositionControlParametersConfig::yaw_rate_i)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PositionControlParametersConfig::AbstractParamDescriptionConstPtr(new PositionControlParametersConfig::ParamDescription<double>("yaw_rate_i", "double", 0, "Yaw-rate controller integrator gain", "", &PositionControlParametersConfig::yaw_rate_i)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.yaw_rate_d = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.yaw_rate_d = 10.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.yaw_rate_d = 5.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PositionControlParametersConfig::AbstractParamDescriptionConstPtr(new PositionControlParametersConfig::ParamDescription<double>("yaw_rate_d", "double", 0, "Yaw-rate controller derivator gain", "", &PositionControlParametersConfig::yaw_rate_d)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PositionControlParametersConfig::AbstractParamDescriptionConstPtr(new PositionControlParametersConfig::ParamDescription<double>("yaw_rate_d", "double", 0, "Yaw-rate controller derivator gain", "", &PositionControlParametersConfig::yaw_rate_d)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.yaw_rate_lim_high = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.yaw_rate_lim_high = 50.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.yaw_rate_lim_high = 0.5;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PositionControlParametersConfig::AbstractParamDescriptionConstPtr(new PositionControlParametersConfig::ParamDescription<double>("yaw_rate_lim_high", "double", 0, "Yaw-rate controller limit - high", "", &PositionControlParametersConfig::yaw_rate_lim_high)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PositionControlParametersConfig::AbstractParamDescriptionConstPtr(new PositionControlParametersConfig::ParamDescription<double>("yaw_rate_lim_high", "double", 0, "Yaw-rate controller limit - high", "", &PositionControlParametersConfig::yaw_rate_lim_high)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.yaw_rate_lim_low = -50.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.yaw_rate_lim_low = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.yaw_rate_lim_low = -0.5;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PositionControlParametersConfig::AbstractParamDescriptionConstPtr(new PositionControlParametersConfig::ParamDescription<double>("yaw_rate_lim_low", "double", 0, "Yaw-rate controller limit - low", "", &PositionControlParametersConfig::yaw_rate_lim_low)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PositionControlParametersConfig::AbstractParamDescriptionConstPtr(new PositionControlParametersConfig::ParamDescription<double>("yaw_rate_lim_low", "double", 0, "Yaw-rate controller limit - low", "", &PositionControlParametersConfig::yaw_rate_lim_low)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.ff_vel_x = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.ff_vel_x = 10.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.ff_vel_x = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PositionControlParametersConfig::AbstractParamDescriptionConstPtr(new PositionControlParametersConfig::ParamDescription<double>("ff_vel_x", "double", 0, "Feed-forward velocity gain - x axis", "", &PositionControlParametersConfig::ff_vel_x)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PositionControlParametersConfig::AbstractParamDescriptionConstPtr(new PositionControlParametersConfig::ParamDescription<double>("ff_vel_x", "double", 0, "Feed-forward velocity gain - x axis", "", &PositionControlParametersConfig::ff_vel_x)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.ff_vel_y = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.ff_vel_y = 10.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.ff_vel_y = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PositionControlParametersConfig::AbstractParamDescriptionConstPtr(new PositionControlParametersConfig::ParamDescription<double>("ff_vel_y", "double", 0, "Feed-forward velocity gain - y axis", "", &PositionControlParametersConfig::ff_vel_y)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PositionControlParametersConfig::AbstractParamDescriptionConstPtr(new PositionControlParametersConfig::ParamDescription<double>("ff_vel_y", "double", 0, "Feed-forward velocity gain - y axis", "", &PositionControlParametersConfig::ff_vel_y)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.ff_vel_z = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.ff_vel_z = 10.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.ff_vel_z = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PositionControlParametersConfig::AbstractParamDescriptionConstPtr(new PositionControlParametersConfig::ParamDescription<double>("ff_vel_z", "double", 0, "Feed-forward velocity gain - z axis", "", &PositionControlParametersConfig::ff_vel_z)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PositionControlParametersConfig::AbstractParamDescriptionConstPtr(new PositionControlParametersConfig::ParamDescription<double>("ff_vel_z", "double", 0, "Feed-forward velocity gain - z axis", "", &PositionControlParametersConfig::ff_vel_z)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.ff_acc_x = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.ff_acc_x = 10.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.ff_acc_x = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PositionControlParametersConfig::AbstractParamDescriptionConstPtr(new PositionControlParametersConfig::ParamDescription<double>("ff_acc_x", "double", 0, "Feed-forward acceleration gain - x axis", "", &PositionControlParametersConfig::ff_acc_x)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PositionControlParametersConfig::AbstractParamDescriptionConstPtr(new PositionControlParametersConfig::ParamDescription<double>("ff_acc_x", "double", 0, "Feed-forward acceleration gain - x axis", "", &PositionControlParametersConfig::ff_acc_x)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.ff_acc_y = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.ff_acc_y = 10.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.ff_acc_y = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PositionControlParametersConfig::AbstractParamDescriptionConstPtr(new PositionControlParametersConfig::ParamDescription<double>("ff_acc_y", "double", 0, "Feed-forward acceleration gain - y axis", "", &PositionControlParametersConfig::ff_acc_y)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PositionControlParametersConfig::AbstractParamDescriptionConstPtr(new PositionControlParametersConfig::ParamDescription<double>("ff_acc_y", "double", 0, "Feed-forward acceleration gain - y axis", "", &PositionControlParametersConfig::ff_acc_y)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.ff_acc_z = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.ff_acc_z = 10.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.ff_acc_z = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(PositionControlParametersConfig::AbstractParamDescriptionConstPtr(new PositionControlParametersConfig::ParamDescription<double>("ff_acc_z", "double", 0, "Feed-forward acceleration gain - z axis", "", &PositionControlParametersConfig::ff_acc_z)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(PositionControlParametersConfig::AbstractParamDescriptionConstPtr(new PositionControlParametersConfig::ParamDescription<double>("ff_acc_z", "double", 0, "Feed-forward acceleration gain - z axis", "", &PositionControlParametersConfig::ff_acc_z)));
//#line 246 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.convertParams();
//#line 246 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(PositionControlParametersConfig::AbstractGroupDescriptionConstPtr(new PositionControlParametersConfig::GroupDescription<PositionControlParametersConfig::DEFAULT, PositionControlParametersConfig>(Default)));
//#line 369 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

      for (std::vector<PositionControlParametersConfig::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__);
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__);
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__);
    }
    std::vector<PositionControlParametersConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<PositionControlParametersConfig::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    PositionControlParametersConfig __max__;
    PositionControlParametersConfig __min__;
    PositionControlParametersConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const PositionControlParametersConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static PositionControlParametersConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &PositionControlParametersConfig::__getDescriptionMessage__()
  {
    return __get_statics__()->__description_message__;
  }

  inline const PositionControlParametersConfig &PositionControlParametersConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }

  inline const PositionControlParametersConfig &PositionControlParametersConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }

  inline const PositionControlParametersConfig &PositionControlParametersConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }

  inline const std::vector<PositionControlParametersConfig::AbstractParamDescriptionConstPtr> &PositionControlParametersConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<PositionControlParametersConfig::AbstractGroupDescriptionConstPtr> &PositionControlParametersConfig::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const PositionControlParametersConfigStatics *PositionControlParametersConfig::__get_statics__()
  {
    const static PositionControlParametersConfigStatics *statics;

    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = PositionControlParametersConfigStatics::get_instance();

    return statics;
  }


}

#undef DYNAMIC_RECONFIGURE_FINAL

#endif // __POSITIONCONTROLPARAMETERSRECONFIGURATOR_H__
