// Generated by gencpp from file uav_ros_msgs/ArmAndTakeoff.msg
// DO NOT EDIT!


#ifndef UAV_ROS_MSGS_MESSAGE_ARMANDTAKEOFF_H
#define UAV_ROS_MSGS_MESSAGE_ARMANDTAKEOFF_H

#include <ros/service_traits.h>


#include <uav_ros_msgs/ArmAndTakeoffRequest.h>
#include <uav_ros_msgs/ArmAndTakeoffResponse.h>


namespace uav_ros_msgs
{

struct ArmAndTakeoff
{

typedef ArmAndTakeoffRequest Request;
typedef ArmAndTakeoffResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ArmAndTakeoff
} // namespace uav_ros_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::uav_ros_msgs::ArmAndTakeoff > {
  static const char* value()
  {
    return "e6f4e586b62777d5287c8002007fb7d3";
  }

  static const char* value(const ::uav_ros_msgs::ArmAndTakeoff&) { return value(); }
};

template<>
struct DataType< ::uav_ros_msgs::ArmAndTakeoff > {
  static const char* value()
  {
    return "uav_ros_msgs/ArmAndTakeoff";
  }

  static const char* value(const ::uav_ros_msgs::ArmAndTakeoff&) { return value(); }
};


// service_traits::MD5Sum< ::uav_ros_msgs::ArmAndTakeoffRequest> should match
// service_traits::MD5Sum< ::uav_ros_msgs::ArmAndTakeoff >
template<>
struct MD5Sum< ::uav_ros_msgs::ArmAndTakeoffRequest>
{
  static const char* value()
  {
    return MD5Sum< ::uav_ros_msgs::ArmAndTakeoff >::value();
  }
  static const char* value(const ::uav_ros_msgs::ArmAndTakeoffRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::uav_ros_msgs::ArmAndTakeoffRequest> should match
// service_traits::DataType< ::uav_ros_msgs::ArmAndTakeoff >
template<>
struct DataType< ::uav_ros_msgs::ArmAndTakeoffRequest>
{
  static const char* value()
  {
    return DataType< ::uav_ros_msgs::ArmAndTakeoff >::value();
  }
  static const char* value(const ::uav_ros_msgs::ArmAndTakeoffRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::uav_ros_msgs::ArmAndTakeoffResponse> should match
// service_traits::MD5Sum< ::uav_ros_msgs::ArmAndTakeoff >
template<>
struct MD5Sum< ::uav_ros_msgs::ArmAndTakeoffResponse>
{
  static const char* value()
  {
    return MD5Sum< ::uav_ros_msgs::ArmAndTakeoff >::value();
  }
  static const char* value(const ::uav_ros_msgs::ArmAndTakeoffResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::uav_ros_msgs::ArmAndTakeoffResponse> should match
// service_traits::DataType< ::uav_ros_msgs::ArmAndTakeoff >
template<>
struct DataType< ::uav_ros_msgs::ArmAndTakeoffResponse>
{
  static const char* value()
  {
    return DataType< ::uav_ros_msgs::ArmAndTakeoff >::value();
  }
  static const char* value(const ::uav_ros_msgs::ArmAndTakeoffResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // UAV_ROS_MSGS_MESSAGE_ARMANDTAKEOFF_H
