// Generated by gencpp from file uav_ros_msgs/ArmAndTakeoffRequest.msg
// DO NOT EDIT!


#ifndef UAV_ROS_MSGS_MESSAGE_ARMANDTAKEOFFREQUEST_H
#define UAV_ROS_MSGS_MESSAGE_ARMANDTAKEOFFREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace uav_ros_msgs
{
template <class ContainerAllocator>
struct ArmAndTakeoffRequest_
{
  typedef ArmAndTakeoffRequest_<ContainerAllocator> Type;

  ArmAndTakeoffRequest_()
    : rel_alt(0.0)
    , timeout(0.0)
    , enable_carrot(false)
    , set_offboard(false)  {
    }
  ArmAndTakeoffRequest_(const ContainerAllocator& _alloc)
    : rel_alt(0.0)
    , timeout(0.0)
    , enable_carrot(false)
    , set_offboard(false)  {
  (void)_alloc;
    }



   typedef double _rel_alt_type;
  _rel_alt_type rel_alt;

   typedef double _timeout_type;
  _timeout_type timeout;

   typedef uint8_t _enable_carrot_type;
  _enable_carrot_type enable_carrot;

   typedef uint8_t _set_offboard_type;
  _set_offboard_type set_offboard;





  typedef boost::shared_ptr< ::uav_ros_msgs::ArmAndTakeoffRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::uav_ros_msgs::ArmAndTakeoffRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ArmAndTakeoffRequest_

typedef ::uav_ros_msgs::ArmAndTakeoffRequest_<std::allocator<void> > ArmAndTakeoffRequest;

typedef boost::shared_ptr< ::uav_ros_msgs::ArmAndTakeoffRequest > ArmAndTakeoffRequestPtr;
typedef boost::shared_ptr< ::uav_ros_msgs::ArmAndTakeoffRequest const> ArmAndTakeoffRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::uav_ros_msgs::ArmAndTakeoffRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::uav_ros_msgs::ArmAndTakeoffRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::uav_ros_msgs::ArmAndTakeoffRequest_<ContainerAllocator1> & lhs, const ::uav_ros_msgs::ArmAndTakeoffRequest_<ContainerAllocator2> & rhs)
{
  return lhs.rel_alt == rhs.rel_alt &&
    lhs.timeout == rhs.timeout &&
    lhs.enable_carrot == rhs.enable_carrot &&
    lhs.set_offboard == rhs.set_offboard;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::uav_ros_msgs::ArmAndTakeoffRequest_<ContainerAllocator1> & lhs, const ::uav_ros_msgs::ArmAndTakeoffRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace uav_ros_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::uav_ros_msgs::ArmAndTakeoffRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::uav_ros_msgs::ArmAndTakeoffRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::uav_ros_msgs::ArmAndTakeoffRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::uav_ros_msgs::ArmAndTakeoffRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uav_ros_msgs::ArmAndTakeoffRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uav_ros_msgs::ArmAndTakeoffRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::uav_ros_msgs::ArmAndTakeoffRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "687e5f477926d159fc82d1b5f27a426e";
  }

  static const char* value(const ::uav_ros_msgs::ArmAndTakeoffRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x687e5f477926d159ULL;
  static const uint64_t static_value2 = 0xfc82d1b5f27a426eULL;
};

template<class ContainerAllocator>
struct DataType< ::uav_ros_msgs::ArmAndTakeoffRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uav_ros_msgs/ArmAndTakeoffRequest";
  }

  static const char* value(const ::uav_ros_msgs::ArmAndTakeoffRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::uav_ros_msgs::ArmAndTakeoffRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 rel_alt\n"
"float64 timeout\n"
"bool enable_carrot\n"
"bool set_offboard\n"
;
  }

  static const char* value(const ::uav_ros_msgs::ArmAndTakeoffRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::uav_ros_msgs::ArmAndTakeoffRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.rel_alt);
      stream.next(m.timeout);
      stream.next(m.enable_carrot);
      stream.next(m.set_offboard);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ArmAndTakeoffRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::uav_ros_msgs::ArmAndTakeoffRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::uav_ros_msgs::ArmAndTakeoffRequest_<ContainerAllocator>& v)
  {
    s << indent << "rel_alt: ";
    Printer<double>::stream(s, indent + "  ", v.rel_alt);
    s << indent << "timeout: ";
    Printer<double>::stream(s, indent + "  ", v.timeout);
    s << indent << "enable_carrot: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.enable_carrot);
    s << indent << "set_offboard: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.set_offboard);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UAV_ROS_MSGS_MESSAGE_ARMANDTAKEOFFREQUEST_H
