// Generated by gencpp from file uav_ros_msgs/GeoBrickApproachResponse.msg
// DO NOT EDIT!


#ifndef UAV_ROS_MSGS_MESSAGE_GEOBRICKAPPROACHRESPONSE_H
#define UAV_ROS_MSGS_MESSAGE_GEOBRICKAPPROACHRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace uav_ros_msgs
{
template <class ContainerAllocator>
struct GeoBrickApproachResponse_
{
  typedef GeoBrickApproachResponse_<ContainerAllocator> Type;

  GeoBrickApproachResponse_()
    : status(false)  {
    }
  GeoBrickApproachResponse_(const ContainerAllocator& _alloc)
    : status(false)  {
  (void)_alloc;
    }



   typedef uint8_t _status_type;
  _status_type status;





  typedef boost::shared_ptr< ::uav_ros_msgs::GeoBrickApproachResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::uav_ros_msgs::GeoBrickApproachResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GeoBrickApproachResponse_

typedef ::uav_ros_msgs::GeoBrickApproachResponse_<std::allocator<void> > GeoBrickApproachResponse;

typedef boost::shared_ptr< ::uav_ros_msgs::GeoBrickApproachResponse > GeoBrickApproachResponsePtr;
typedef boost::shared_ptr< ::uav_ros_msgs::GeoBrickApproachResponse const> GeoBrickApproachResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::uav_ros_msgs::GeoBrickApproachResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::uav_ros_msgs::GeoBrickApproachResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::uav_ros_msgs::GeoBrickApproachResponse_<ContainerAllocator1> & lhs, const ::uav_ros_msgs::GeoBrickApproachResponse_<ContainerAllocator2> & rhs)
{
  return lhs.status == rhs.status;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::uav_ros_msgs::GeoBrickApproachResponse_<ContainerAllocator1> & lhs, const ::uav_ros_msgs::GeoBrickApproachResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace uav_ros_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::uav_ros_msgs::GeoBrickApproachResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::uav_ros_msgs::GeoBrickApproachResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::uav_ros_msgs::GeoBrickApproachResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::uav_ros_msgs::GeoBrickApproachResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uav_ros_msgs::GeoBrickApproachResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uav_ros_msgs::GeoBrickApproachResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::uav_ros_msgs::GeoBrickApproachResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3a1255d4d998bd4d6585c64639b5ee9a";
  }

  static const char* value(const ::uav_ros_msgs::GeoBrickApproachResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3a1255d4d998bd4dULL;
  static const uint64_t static_value2 = 0x6585c64639b5ee9aULL;
};

template<class ContainerAllocator>
struct DataType< ::uav_ros_msgs::GeoBrickApproachResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uav_ros_msgs/GeoBrickApproachResponse";
  }

  static const char* value(const ::uav_ros_msgs::GeoBrickApproachResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::uav_ros_msgs::GeoBrickApproachResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool status\n"
;
  }

  static const char* value(const ::uav_ros_msgs::GeoBrickApproachResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::uav_ros_msgs::GeoBrickApproachResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GeoBrickApproachResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::uav_ros_msgs::GeoBrickApproachResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::uav_ros_msgs::GeoBrickApproachResponse_<ContainerAllocator>& v)
  {
    s << indent << "status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UAV_ROS_MSGS_MESSAGE_GEOBRICKAPPROACHRESPONSE_H
