// Generated by gencpp from file uav_ros_msgs/Land.msg
// DO NOT EDIT!


#ifndef UAV_ROS_MSGS_MESSAGE_LAND_H
#define UAV_ROS_MSGS_MESSAGE_LAND_H

#include <ros/service_traits.h>


#include <uav_ros_msgs/LandRequest.h>
#include <uav_ros_msgs/LandResponse.h>


namespace uav_ros_msgs
{

struct Land
{

typedef LandRequest Request;
typedef LandResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Land
} // namespace uav_ros_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::uav_ros_msgs::Land > {
  static const char* value()
  {
    return "49514ffdb40ecb1526e9c9073a97d150";
  }

  static const char* value(const ::uav_ros_msgs::Land&) { return value(); }
};

template<>
struct DataType< ::uav_ros_msgs::Land > {
  static const char* value()
  {
    return "uav_ros_msgs/Land";
  }

  static const char* value(const ::uav_ros_msgs::Land&) { return value(); }
};


// service_traits::MD5Sum< ::uav_ros_msgs::LandRequest> should match
// service_traits::MD5Sum< ::uav_ros_msgs::Land >
template<>
struct MD5Sum< ::uav_ros_msgs::LandRequest>
{
  static const char* value()
  {
    return MD5Sum< ::uav_ros_msgs::Land >::value();
  }
  static const char* value(const ::uav_ros_msgs::LandRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::uav_ros_msgs::LandRequest> should match
// service_traits::DataType< ::uav_ros_msgs::Land >
template<>
struct DataType< ::uav_ros_msgs::LandRequest>
{
  static const char* value()
  {
    return DataType< ::uav_ros_msgs::Land >::value();
  }
  static const char* value(const ::uav_ros_msgs::LandRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::uav_ros_msgs::LandResponse> should match
// service_traits::MD5Sum< ::uav_ros_msgs::Land >
template<>
struct MD5Sum< ::uav_ros_msgs::LandResponse>
{
  static const char* value()
  {
    return MD5Sum< ::uav_ros_msgs::Land >::value();
  }
  static const char* value(const ::uav_ros_msgs::LandResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::uav_ros_msgs::LandResponse> should match
// service_traits::DataType< ::uav_ros_msgs::Land >
template<>
struct DataType< ::uav_ros_msgs::LandResponse>
{
  static const char* value()
  {
    return DataType< ::uav_ros_msgs::Land >::value();
  }
  static const char* value(const ::uav_ros_msgs::LandResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // UAV_ROS_MSGS_MESSAGE_LAND_H
