// Generated by gencpp from file uav_ros_msgs/LandRequest.msg
// DO NOT EDIT!


#ifndef UAV_ROS_MSGS_MESSAGE_LANDREQUEST_H
#define UAV_ROS_MSGS_MESSAGE_LANDREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace uav_ros_msgs
{
template <class ContainerAllocator>
struct LandRequest_
{
  typedef LandRequest_<ContainerAllocator> Type;

  LandRequest_()
    : force_land(false)  {
    }
  LandRequest_(const ContainerAllocator& _alloc)
    : force_land(false)  {
  (void)_alloc;
    }



   typedef uint8_t _force_land_type;
  _force_land_type force_land;





  typedef boost::shared_ptr< ::uav_ros_msgs::LandRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::uav_ros_msgs::LandRequest_<ContainerAllocator> const> ConstPtr;

}; // struct LandRequest_

typedef ::uav_ros_msgs::LandRequest_<std::allocator<void> > LandRequest;

typedef boost::shared_ptr< ::uav_ros_msgs::LandRequest > LandRequestPtr;
typedef boost::shared_ptr< ::uav_ros_msgs::LandRequest const> LandRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::uav_ros_msgs::LandRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::uav_ros_msgs::LandRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::uav_ros_msgs::LandRequest_<ContainerAllocator1> & lhs, const ::uav_ros_msgs::LandRequest_<ContainerAllocator2> & rhs)
{
  return lhs.force_land == rhs.force_land;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::uav_ros_msgs::LandRequest_<ContainerAllocator1> & lhs, const ::uav_ros_msgs::LandRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace uav_ros_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::uav_ros_msgs::LandRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::uav_ros_msgs::LandRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::uav_ros_msgs::LandRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::uav_ros_msgs::LandRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uav_ros_msgs::LandRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uav_ros_msgs::LandRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::uav_ros_msgs::LandRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2d0504ae245a8aa66b2959eea8c8943b";
  }

  static const char* value(const ::uav_ros_msgs::LandRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2d0504ae245a8aa6ULL;
  static const uint64_t static_value2 = 0x6b2959eea8c8943bULL;
};

template<class ContainerAllocator>
struct DataType< ::uav_ros_msgs::LandRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uav_ros_msgs/LandRequest";
  }

  static const char* value(const ::uav_ros_msgs::LandRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::uav_ros_msgs::LandRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool force_land\n"
;
  }

  static const char* value(const ::uav_ros_msgs::LandRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::uav_ros_msgs::LandRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.force_land);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LandRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::uav_ros_msgs::LandRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::uav_ros_msgs::LandRequest_<ContainerAllocator>& v)
  {
    s << indent << "force_land: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.force_land);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UAV_ROS_MSGS_MESSAGE_LANDREQUEST_H
