// Generated by gencpp from file uav_ros_msgs/TakeOffResponse.msg
// DO NOT EDIT!


#ifndef UAV_ROS_MSGS_MESSAGE_TAKEOFFRESPONSE_H
#define UAV_ROS_MSGS_MESSAGE_TAKEOFFRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace uav_ros_msgs
{
template <class ContainerAllocator>
struct TakeOffResponse_
{
  typedef TakeOffResponse_<ContainerAllocator> Type;

  TakeOffResponse_()
    : success(false)
    , message()  {
    }
  TakeOffResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , message(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _message_type;
  _message_type message;





  typedef boost::shared_ptr< ::uav_ros_msgs::TakeOffResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::uav_ros_msgs::TakeOffResponse_<ContainerAllocator> const> ConstPtr;

}; // struct TakeOffResponse_

typedef ::uav_ros_msgs::TakeOffResponse_<std::allocator<void> > TakeOffResponse;

typedef boost::shared_ptr< ::uav_ros_msgs::TakeOffResponse > TakeOffResponsePtr;
typedef boost::shared_ptr< ::uav_ros_msgs::TakeOffResponse const> TakeOffResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::uav_ros_msgs::TakeOffResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::uav_ros_msgs::TakeOffResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::uav_ros_msgs::TakeOffResponse_<ContainerAllocator1> & lhs, const ::uav_ros_msgs::TakeOffResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success &&
    lhs.message == rhs.message;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::uav_ros_msgs::TakeOffResponse_<ContainerAllocator1> & lhs, const ::uav_ros_msgs::TakeOffResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace uav_ros_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::uav_ros_msgs::TakeOffResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::uav_ros_msgs::TakeOffResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::uav_ros_msgs::TakeOffResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::uav_ros_msgs::TakeOffResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uav_ros_msgs::TakeOffResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uav_ros_msgs::TakeOffResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::uav_ros_msgs::TakeOffResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "937c9679a518e3a18d831e57125ea522";
  }

  static const char* value(const ::uav_ros_msgs::TakeOffResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x937c9679a518e3a1ULL;
  static const uint64_t static_value2 = 0x8d831e57125ea522ULL;
};

template<class ContainerAllocator>
struct DataType< ::uav_ros_msgs::TakeOffResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uav_ros_msgs/TakeOffResponse";
  }

  static const char* value(const ::uav_ros_msgs::TakeOffResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::uav_ros_msgs::TakeOffResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
"string message\n"
"\n"
;
  }

  static const char* value(const ::uav_ros_msgs::TakeOffResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::uav_ros_msgs::TakeOffResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TakeOffResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::uav_ros_msgs::TakeOffResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::uav_ros_msgs::TakeOffResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UAV_ROS_MSGS_MESSAGE_TAKEOFFRESPONSE_H
