// Generated by gencpp from file uav_ros_msgs/TakeOff.msg
// DO NOT EDIT!


#ifndef UAV_ROS_MSGS_MESSAGE_TAKEOFF_H
#define UAV_ROS_MSGS_MESSAGE_TAKEOFF_H

#include <ros/service_traits.h>


#include <uav_ros_msgs/TakeOffRequest.h>
#include <uav_ros_msgs/TakeOffResponse.h>


namespace uav_ros_msgs
{

struct TakeOff
{

typedef TakeOffRequest Request;
typedef TakeOffResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct TakeOff
} // namespace uav_ros_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::uav_ros_msgs::TakeOff > {
  static const char* value()
  {
    return "c6208ecabfc99527ac999c2742ee1a42";
  }

  static const char* value(const ::uav_ros_msgs::TakeOff&) { return value(); }
};

template<>
struct DataType< ::uav_ros_msgs::TakeOff > {
  static const char* value()
  {
    return "uav_ros_msgs/TakeOff";
  }

  static const char* value(const ::uav_ros_msgs::TakeOff&) { return value(); }
};


// service_traits::MD5Sum< ::uav_ros_msgs::TakeOffRequest> should match
// service_traits::MD5Sum< ::uav_ros_msgs::TakeOff >
template<>
struct MD5Sum< ::uav_ros_msgs::TakeOffRequest>
{
  static const char* value()
  {
    return MD5Sum< ::uav_ros_msgs::TakeOff >::value();
  }
  static const char* value(const ::uav_ros_msgs::TakeOffRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::uav_ros_msgs::TakeOffRequest> should match
// service_traits::DataType< ::uav_ros_msgs::TakeOff >
template<>
struct DataType< ::uav_ros_msgs::TakeOffRequest>
{
  static const char* value()
  {
    return DataType< ::uav_ros_msgs::TakeOff >::value();
  }
  static const char* value(const ::uav_ros_msgs::TakeOffRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::uav_ros_msgs::TakeOffResponse> should match
// service_traits::MD5Sum< ::uav_ros_msgs::TakeOff >
template<>
struct MD5Sum< ::uav_ros_msgs::TakeOffResponse>
{
  static const char* value()
  {
    return MD5Sum< ::uav_ros_msgs::TakeOff >::value();
  }
  static const char* value(const ::uav_ros_msgs::TakeOffResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::uav_ros_msgs::TakeOffResponse> should match
// service_traits::DataType< ::uav_ros_msgs::TakeOff >
template<>
struct DataType< ::uav_ros_msgs::TakeOffResponse>
{
  static const char* value()
  {
    return DataType< ::uav_ros_msgs::TakeOff >::value();
  }
  static const char* value(const ::uav_ros_msgs::TakeOffResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // UAV_ROS_MSGS_MESSAGE_TAKEOFF_H
