// Generated by gencpp from file uav_ros_msgs/TakeOffRequest.msg
// DO NOT EDIT!


#ifndef UAV_ROS_MSGS_MESSAGE_TAKEOFFREQUEST_H
#define UAV_ROS_MSGS_MESSAGE_TAKEOFFREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace uav_ros_msgs
{
template <class ContainerAllocator>
struct TakeOffRequest_
{
  typedef TakeOffRequest_<ContainerAllocator> Type;

  TakeOffRequest_()
    : rel_alt(0.0)  {
    }
  TakeOffRequest_(const ContainerAllocator& _alloc)
    : rel_alt(0.0)  {
  (void)_alloc;
    }



   typedef double _rel_alt_type;
  _rel_alt_type rel_alt;





  typedef boost::shared_ptr< ::uav_ros_msgs::TakeOffRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::uav_ros_msgs::TakeOffRequest_<ContainerAllocator> const> ConstPtr;

}; // struct TakeOffRequest_

typedef ::uav_ros_msgs::TakeOffRequest_<std::allocator<void> > TakeOffRequest;

typedef boost::shared_ptr< ::uav_ros_msgs::TakeOffRequest > TakeOffRequestPtr;
typedef boost::shared_ptr< ::uav_ros_msgs::TakeOffRequest const> TakeOffRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::uav_ros_msgs::TakeOffRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::uav_ros_msgs::TakeOffRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::uav_ros_msgs::TakeOffRequest_<ContainerAllocator1> & lhs, const ::uav_ros_msgs::TakeOffRequest_<ContainerAllocator2> & rhs)
{
  return lhs.rel_alt == rhs.rel_alt;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::uav_ros_msgs::TakeOffRequest_<ContainerAllocator1> & lhs, const ::uav_ros_msgs::TakeOffRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace uav_ros_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::uav_ros_msgs::TakeOffRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::uav_ros_msgs::TakeOffRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::uav_ros_msgs::TakeOffRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::uav_ros_msgs::TakeOffRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uav_ros_msgs::TakeOffRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uav_ros_msgs::TakeOffRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::uav_ros_msgs::TakeOffRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "182aa7fa9ebe5b922331b91449afb759";
  }

  static const char* value(const ::uav_ros_msgs::TakeOffRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x182aa7fa9ebe5b92ULL;
  static const uint64_t static_value2 = 0x2331b91449afb759ULL;
};

template<class ContainerAllocator>
struct DataType< ::uav_ros_msgs::TakeOffRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uav_ros_msgs/TakeOffRequest";
  }

  static const char* value(const ::uav_ros_msgs::TakeOffRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::uav_ros_msgs::TakeOffRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 rel_alt\n"
;
  }

  static const char* value(const ::uav_ros_msgs::TakeOffRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::uav_ros_msgs::TakeOffRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.rel_alt);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TakeOffRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::uav_ros_msgs::TakeOffRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::uav_ros_msgs::TakeOffRequest_<ContainerAllocator>& v)
  {
    s << indent << "rel_alt: ";
    Printer<double>::stream(s, indent + "  ", v.rel_alt);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UAV_ROS_MSGS_MESSAGE_TAKEOFFREQUEST_H
