// Generated by gencpp from file uav_ros_msgs/VisualServoProcessValues.msg
// DO NOT EDIT!


#ifndef UAV_ROS_MSGS_MESSAGE_VISUALSERVOPROCESSVALUES_H
#define UAV_ROS_MSGS_MESSAGE_VISUALSERVOPROCESSVALUES_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace uav_ros_msgs
{
template <class ContainerAllocator>
struct VisualServoProcessValues_
{
  typedef VisualServoProcessValues_<ContainerAllocator> Type;

  VisualServoProcessValues_()
    : header()
    , x(0.0)
    , y(0.0)
    , z(0.0)
    , yaw(0.0)  {
    }
  VisualServoProcessValues_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , x(0.0)
    , y(0.0)
    , z(0.0)
    , yaw(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef float _z_type;
  _z_type z;

   typedef float _yaw_type;
  _yaw_type yaw;





  typedef boost::shared_ptr< ::uav_ros_msgs::VisualServoProcessValues_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::uav_ros_msgs::VisualServoProcessValues_<ContainerAllocator> const> ConstPtr;

}; // struct VisualServoProcessValues_

typedef ::uav_ros_msgs::VisualServoProcessValues_<std::allocator<void> > VisualServoProcessValues;

typedef boost::shared_ptr< ::uav_ros_msgs::VisualServoProcessValues > VisualServoProcessValuesPtr;
typedef boost::shared_ptr< ::uav_ros_msgs::VisualServoProcessValues const> VisualServoProcessValuesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::uav_ros_msgs::VisualServoProcessValues_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::uav_ros_msgs::VisualServoProcessValues_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::uav_ros_msgs::VisualServoProcessValues_<ContainerAllocator1> & lhs, const ::uav_ros_msgs::VisualServoProcessValues_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.z == rhs.z &&
    lhs.yaw == rhs.yaw;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::uav_ros_msgs::VisualServoProcessValues_<ContainerAllocator1> & lhs, const ::uav_ros_msgs::VisualServoProcessValues_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace uav_ros_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::uav_ros_msgs::VisualServoProcessValues_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::uav_ros_msgs::VisualServoProcessValues_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::uav_ros_msgs::VisualServoProcessValues_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::uav_ros_msgs::VisualServoProcessValues_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uav_ros_msgs::VisualServoProcessValues_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uav_ros_msgs::VisualServoProcessValues_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::uav_ros_msgs::VisualServoProcessValues_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fb9bb23ad995963ed72488318d105adf";
  }

  static const char* value(const ::uav_ros_msgs::VisualServoProcessValues_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfb9bb23ad995963eULL;
  static const uint64_t static_value2 = 0xd72488318d105adfULL;
};

template<class ContainerAllocator>
struct DataType< ::uav_ros_msgs::VisualServoProcessValues_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uav_ros_msgs/VisualServoProcessValues";
  }

  static const char* value(const ::uav_ros_msgs::VisualServoProcessValues_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::uav_ros_msgs::VisualServoProcessValues_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"\n"
"float32 x\n"
"float32 y\n"
"float32 z\n"
"float32 yaw\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::uav_ros_msgs::VisualServoProcessValues_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::uav_ros_msgs::VisualServoProcessValues_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
      stream.next(m.yaw);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct VisualServoProcessValues_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::uav_ros_msgs::VisualServoProcessValues_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::uav_ros_msgs::VisualServoProcessValues_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<float>::stream(s, indent + "  ", v.z);
    s << indent << "yaw: ";
    Printer<float>::stream(s, indent + "  ", v.yaw);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UAV_ROS_MSGS_MESSAGE_VISUALSERVOPROCESSVALUES_H
