// Generated by gencpp from file uav_ros_msgs/Waypoint.msg
// DO NOT EDIT!


#ifndef UAV_ROS_MSGS_MESSAGE_WAYPOINT_H
#define UAV_ROS_MSGS_MESSAGE_WAYPOINT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/PoseStamped.h>
#include <uav_ros_msgs/Task.h>

namespace uav_ros_msgs
{
template <class ContainerAllocator>
struct Waypoint_
{
  typedef Waypoint_<ContainerAllocator> Type;

  Waypoint_()
    : pose()
    , waiting_time(0.0)
    , tasks()  {
    }
  Waypoint_(const ContainerAllocator& _alloc)
    : pose(_alloc)
    , waiting_time(0.0)
    , tasks(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::PoseStamped_<ContainerAllocator>  _pose_type;
  _pose_type pose;

   typedef double _waiting_time_type;
  _waiting_time_type waiting_time;

   typedef std::vector< ::uav_ros_msgs::Task_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::uav_ros_msgs::Task_<ContainerAllocator> >> _tasks_type;
  _tasks_type tasks;





  typedef boost::shared_ptr< ::uav_ros_msgs::Waypoint_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::uav_ros_msgs::Waypoint_<ContainerAllocator> const> ConstPtr;

}; // struct Waypoint_

typedef ::uav_ros_msgs::Waypoint_<std::allocator<void> > Waypoint;

typedef boost::shared_ptr< ::uav_ros_msgs::Waypoint > WaypointPtr;
typedef boost::shared_ptr< ::uav_ros_msgs::Waypoint const> WaypointConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::uav_ros_msgs::Waypoint_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::uav_ros_msgs::Waypoint_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::uav_ros_msgs::Waypoint_<ContainerAllocator1> & lhs, const ::uav_ros_msgs::Waypoint_<ContainerAllocator2> & rhs)
{
  return lhs.pose == rhs.pose &&
    lhs.waiting_time == rhs.waiting_time &&
    lhs.tasks == rhs.tasks;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::uav_ros_msgs::Waypoint_<ContainerAllocator1> & lhs, const ::uav_ros_msgs::Waypoint_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace uav_ros_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::uav_ros_msgs::Waypoint_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::uav_ros_msgs::Waypoint_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::uav_ros_msgs::Waypoint_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::uav_ros_msgs::Waypoint_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uav_ros_msgs::Waypoint_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uav_ros_msgs::Waypoint_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::uav_ros_msgs::Waypoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2d1bf9520d02f7e30509702852aa280c";
  }

  static const char* value(const ::uav_ros_msgs::Waypoint_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2d1bf9520d02f7e3ULL;
  static const uint64_t static_value2 = 0x0509702852aa280cULL;
};

template<class ContainerAllocator>
struct DataType< ::uav_ros_msgs::Waypoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uav_ros_msgs/Waypoint";
  }

  static const char* value(const ::uav_ros_msgs::Waypoint_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::uav_ros_msgs::Waypoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/PoseStamped   pose\n"
"float64                     waiting_time\n"
"uav_ros_msgs/Task[]         tasks\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseStamped\n"
"# A Pose with reference coordinate frame and timestamp\n"
"Header header\n"
"Pose pose\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
"\n"
"================================================================================\n"
"MSG: uav_ros_msgs/Task\n"
"string PICKUP_TASK = \"PickupTask\"\n"
"string DROPOFF_TASK = \"DropoffTask\"\n"
"\n"
"std_msgs/Header header\n"
"int32 id\n"
"string name\n"
"string type\n"
"float64 timeout\n"
;
  }

  static const char* value(const ::uav_ros_msgs::Waypoint_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::uav_ros_msgs::Waypoint_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pose);
      stream.next(m.waiting_time);
      stream.next(m.tasks);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Waypoint_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::uav_ros_msgs::Waypoint_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::uav_ros_msgs::Waypoint_<ContainerAllocator>& v)
  {
    s << indent << "pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
    s << indent << "waiting_time: ";
    Printer<double>::stream(s, indent + "  ", v.waiting_time);
    s << indent << "tasks[]" << std::endl;
    for (size_t i = 0; i < v.tasks.size(); ++i)
    {
      s << indent << "  tasks[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::uav_ros_msgs::Task_<ContainerAllocator> >::stream(s, indent + "    ", v.tasks[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // UAV_ROS_MSGS_MESSAGE_WAYPOINT_H
