// Generated by gencpp from file uav_ros_msgs/Waypoints.msg
// DO NOT EDIT!


#ifndef UAV_ROS_MSGS_MESSAGE_WAYPOINTS_H
#define UAV_ROS_MSGS_MESSAGE_WAYPOINTS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <uav_ros_msgs/Waypoint.h>

namespace uav_ros_msgs
{
template <class ContainerAllocator>
struct Waypoints_
{
  typedef Waypoints_<ContainerAllocator> Type;

  Waypoints_()
    : waypoints()  {
    }
  Waypoints_(const ContainerAllocator& _alloc)
    : waypoints(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::uav_ros_msgs::Waypoint_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::uav_ros_msgs::Waypoint_<ContainerAllocator> >> _waypoints_type;
  _waypoints_type waypoints;





  typedef boost::shared_ptr< ::uav_ros_msgs::Waypoints_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::uav_ros_msgs::Waypoints_<ContainerAllocator> const> ConstPtr;

}; // struct Waypoints_

typedef ::uav_ros_msgs::Waypoints_<std::allocator<void> > Waypoints;

typedef boost::shared_ptr< ::uav_ros_msgs::Waypoints > WaypointsPtr;
typedef boost::shared_ptr< ::uav_ros_msgs::Waypoints const> WaypointsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::uav_ros_msgs::Waypoints_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::uav_ros_msgs::Waypoints_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::uav_ros_msgs::Waypoints_<ContainerAllocator1> & lhs, const ::uav_ros_msgs::Waypoints_<ContainerAllocator2> & rhs)
{
  return lhs.waypoints == rhs.waypoints;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::uav_ros_msgs::Waypoints_<ContainerAllocator1> & lhs, const ::uav_ros_msgs::Waypoints_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace uav_ros_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::uav_ros_msgs::Waypoints_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::uav_ros_msgs::Waypoints_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::uav_ros_msgs::Waypoints_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::uav_ros_msgs::Waypoints_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uav_ros_msgs::Waypoints_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uav_ros_msgs::Waypoints_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::uav_ros_msgs::Waypoints_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e90836ac7c988e433ee38604b728daf9";
  }

  static const char* value(const ::uav_ros_msgs::Waypoints_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe90836ac7c988e43ULL;
  static const uint64_t static_value2 = 0x3ee38604b728daf9ULL;
};

template<class ContainerAllocator>
struct DataType< ::uav_ros_msgs::Waypoints_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uav_ros_msgs/Waypoints";
  }

  static const char* value(const ::uav_ros_msgs::Waypoints_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::uav_ros_msgs::Waypoints_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uav_ros_msgs/Waypoint[]     waypoints\n"
"================================================================================\n"
"MSG: uav_ros_msgs/Waypoint\n"
"geometry_msgs/PoseStamped   pose\n"
"float64                     waiting_time\n"
"uav_ros_msgs/Task[]         tasks\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseStamped\n"
"# A Pose with reference coordinate frame and timestamp\n"
"Header header\n"
"Pose pose\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
"\n"
"================================================================================\n"
"MSG: uav_ros_msgs/Task\n"
"string PICKUP_TASK = \"PickupTask\"\n"
"string DROPOFF_TASK = \"DropoffTask\"\n"
"\n"
"std_msgs/Header header\n"
"int32 id\n"
"string name\n"
"string type\n"
"float64 timeout\n"
;
  }

  static const char* value(const ::uav_ros_msgs::Waypoints_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::uav_ros_msgs::Waypoints_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.waypoints);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Waypoints_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::uav_ros_msgs::Waypoints_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::uav_ros_msgs::Waypoints_<ContainerAllocator>& v)
  {
    s << indent << "waypoints[]" << std::endl;
    for (size_t i = 0; i < v.waypoints.size(); ++i)
    {
      s << indent << "  waypoints[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::uav_ros_msgs::Waypoint_<ContainerAllocator> >::stream(s, indent + "    ", v.waypoints[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // UAV_ROS_MSGS_MESSAGE_WAYPOINTS_H
