(cl:defpackage topp_ros-srv
  (:use )
  (:export
   "GENERATETRAJECTORY"
   "<GENERATETRAJECTORY-REQUEST>"
   "GENERATETRAJECTORY-REQUEST"
   "<GENERATETRAJECTORY-RESPONSE>"
   "GENERATETRAJECTORY-RESPONSE"
   "GETHELIXPOINTS"
   "<GETHELIXPOINTS-REQUEST>"
   "GETHELIXPOINTS-REQUEST"
   "<GETHELIXPOINTS-RESPONSE>"
   "GETHELIXPOINTS-RESPONSE"
  ))

