(cl:in-package ros_vrpn_client-msg)
(cl:export '(HEADER-VAL
          HEADER
          POS_MEASURED-VAL
          POS_MEASURED
          POS_OLD-VAL
          POS_OLD
          VEL_OLD-VAL
          VEL_OLD
          POS_EST-VAL
          POS_EST
          VEL_EST-VAL
          VEL_EST
          QUAT_MEASURED-VAL
          QUAT_MEASURED
          QUAT_OLD-VAL
          QUAT_OLD
          OMEGA_OLD-VAL
          OMEGA_OLD
          QUAT_EST-VAL
          QUAT_EST
          OMEGA_EST-VAL
          OMEGA_EST
          COVARIANCE-VAL
          COVARIANCE
          Q_COVARIANCE_TRACE-VAL
          Q_COVARIANCE_TRACE
          OUTLIER_FLAG-VAL
          OUTLIER_FLAG
          MEASUREMENT_FLIP_FLAG-VAL
          MEASUREMENT_FLIP_FLAG
          Q_Z_Z1_MAGNITUDE-VAL
          Q_Z_Z1_MAGNITUDE
          Q_Z_B_MAHALANOBIS_DISTANCE-VAL
          Q_Z_B_MAHALANOBIS_DISTANCE
))