(cl:defpackage uav_ros_msgs-srv
  (:use )
  (:export
   "ARMANDTAKEOFF"
   "<ARMANDTAKEOFF-REQUEST>"
   "ARMANDTAKEOFF-REQUEST"
   "<ARMANDTAKEOFF-RESPONSE>"
   "ARMANDTAKEOFF-RESPONSE"
   "GEOBRICKAPPROACH"
   "<GEOBRICKAPPROACH-REQUEST>"
   "GEOBRICKAPPROACH-REQUEST"
   "<GEOBRICKAPPROACH-RESPONSE>"
   "GEOBRICKAPPROACH-RESPONSE"
   "LAND"
   "<LAND-REQUEST>"
   "LAND-REQUEST"
   "<LAND-RESPONSE>"
   "LAND-RESPONSE"
   "TAKEOFF"
   "<TAKEOFF-REQUEST>"
   "TAKEOFF-REQUEST"
   "<TAKEOFF-RESPONSE>"
   "TAKEOFF-RESPONSE"
  ))

